#!/usr/bin/env bash

# 📊 ÍNDICE VISUAL DEL PROYECTO

clear

echo ""
echo "╔═══════════════════════════════════════════════════════════════════════╗"
echo "║                                                                       ║"
echo "║          ☕ SISTEMA DE VENTA DE CAFÉ - PROYECTOS COMPLETOS           ║"
echo "║                                                                       ║"
echo "║             Versión Quarkus + Versión JHipster + Documentación      ║"
echo "║                                                                       ║"
echo "╚═══════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📁 ESTRUCTURA DEL PROYECTO"
echo "══════════════════════════════════════════════════════════════════════"
echo ""
echo "Examen_final_taller_4/"
echo "│"
echo "├── 📂 venta-cafe-api/                    ⭐ QUARKUS (LISTO PARA USAR)"
echo "│   ├── Backend Quarkus 3.29.0"
echo "│   ├── Frontend HTML/CSS/JS Vanilla"
echo "│   ├── PostgreSQL Database"
echo "│   ├── Docker & Docker Compose"
echo "│   ├── README_INTERFAZ.md              ← Documentación"
echo "│   ├── DOCKER_GUIA.md                  ← Guía Docker"
echo "│   └── 🚀 EJECUTAR: docker-compose up --build"
echo "│"
echo "├── 📂 venta-cafe-jhipster/             ⭐ JHIPSTER (GENERABLE)"
echo "│   ├── venta-cafe.jdl                  ← Modelado completo"
echo "│   ├── generate.sh                     ← Script Linux/macOS"
echo "│   ├── generate.bat                    ← Script Windows"
echo "│   ├── README_JHIPSTER.md              ← Documentación completa"
echo "│   ├── QUICKSTART.md                   ← Guía rápida"
echo "│   └── 🚀 GENERAR: ./generate.bat o ./generate.sh"
echo "│"
echo "├── 📄 README_PRINCIPAL.md              ← ESTE DOCUMENTO (Inicio)"
echo "├── 📄 COMPARATIVA_QUARKUS_JHIPSTER.md  ← Análisis comparativo"
echo "├── 📄 README.md                        ← Original"
echo "└── 📄 pom.xml                          ← Maven principal"
echo ""

echo "═════════════════════════════════════════════════════════════════════════"
echo ""
echo "🎯 OPCIÓN 1: QUARKUS (Ligero, Rápido, Minimalista)"
echo "═════════════════════════════════════════════════════════════════════════"
echo ""
echo "✅ MEJOR PARA:"
echo "   • Prototipos rápidos"
echo "   • Equipos pequeños"
echo "   • Bajo consumo de recursos"
echo "   • APIs ligeras"
echo ""
echo "📊 CARACTERÍSTICAS:"
echo "   • Startup time: < 1 segundo"
echo "   • Memoria: ~100 MB"
echo "   • Frontend: HTML/CSS/JavaScript"
echo "   • Backend: Quarkus REST API"
echo "   • BD: PostgreSQL"
echo "   • Auth: JWT"
echo ""
echo "🚀 INICIO RÁPIDO (5 minutos):"
echo "   $ cd venta-cafe-api"
echo "   $ docker-compose up --build"
echo "   → Abre: http://localhost:8080/index.html"
echo ""
echo "📚 Documentación:"
echo "   • venta-cafe-api/README_INTERFAZ.md"
echo "   • venta-cafe-api/DOCKER_GUIA.md"
echo ""

echo "═════════════════════════════════════════════════════════════════════════"
echo ""
echo "🎨 OPCIÓN 2: JHIPSTER (Profesional, Escalable, Completo)"
echo "═════════════════════════════════════════════════════════════════════════"
echo ""
echo "✅ MEJOR PARA:"
echo "   • Proyectos empresariales"
echo "   • Equipos grandes"
echo "   • UI moderna (React)"
echo "   • Escalabilidad futura"
echo ""
echo "📊 CARACTERÍSTICAS:"
echo "   • Frontend: React 18 + Redux + TypeScript"
echo "   • Backend: Spring Boot 3.x"
echo "   • BD: PostgreSQL + Liquibase"
echo "   • Auth: JWT + OAuth2"
echo "   • Testing: JUnit + Jest + Cypress"
echo "   • Admin UI incluida"
echo ""
echo "🚀 INICIO RÁPIDO (20 minutos):"
echo "   $ cd venta-cafe-jhipster"
echo "   $ ./generate.bat              (Windows)"
echo "   $ ./generate.sh               (Linux/macOS)"
echo "   → Script genera proyecto automáticamente"
echo "   $ cd venta-cafe"
echo "   $ mvn spring-boot:run         (Terminal 1)"
echo "   $ npm start                   (Terminal 2)"
echo "   → Abre: http://localhost:3000"
echo ""
echo "📚 Documentación:"
echo "   • venta-cafe-jhipster/README_JHIPSTER.md"
echo "   • venta-cafe-jhipster/QUICKSTART.md"
echo ""

echo "═════════════════════════════════════════════════════════════════════════"
echo ""
echo "🔄 COMPARATIVA RÁPIDA"
echo "═════════════════════════════════════════════════════════════════════════"
echo ""
echo "Aspecto              │ Quarkus        │ JHipster"
echo "─────────────────────┼────────────────┼─────────────────"
echo "Tiempo instalación   │ 5 min          │ 20 min"
echo "Startup time         │ < 1 seg        │ 5-10 seg"
echo "Memoria RAM          │ 100 MB         │ 400 MB"
echo "Frontend             │ HTML/CSS/JS    │ React 18"
echo "Complejidad          │ Baja           │ Media-Alta"
echo "Escalabilidad        │ ⭐⭐⭐          │ ⭐⭐⭐⭐"
echo "Auditoría            │ Semi-manual    │ Automática"
echo "Admin UI             │ No             │ Sí"
echo "Curva aprendizaje     │ Suave          │ Pronunciada"
echo ""

echo "═════════════════════════════════════════════════════════════════════════"
echo ""
echo "📊 ENTIDADES Y CARACTERÍSTICAS"
echo "═════════════════════════════════════════════════════════════════════════"
echo ""
echo "QUARKUS incluye:"
echo "  ✓ Cafe (Productos)"
echo "  ✓ Cliente (Compradores)"
echo "  ✓ Venta (Transacciones)"
echo "  ✓ Usuario (Vendedores)"
echo "  ✓ Auditoria (Trazabilidad)"
echo ""
echo "JHIPSTER adiciona:"
echo "  ✓ DetalleVenta (Items de ventas)"
echo "  ✓ Cupon (Descuentos y promociones)"
echo "  ✓ Reporte (Análisis y reportes)"
echo "  + Datos de auditoría automática"
echo ""

echo "═════════════════════════════════════════════════════════════════════════"
echo ""
echo "💡 ¿CUÁL ELEGIR?"
echo "═════════════════════════════════════════════════════════════════════════"
echo ""
echo "ELIGE QUARKUS si:"
echo "  ✅ Necesitas MVP rápido"
echo "  ✅ Presupuesto limitado"
echo "  ✅ Pocos recursos disponibles"
echo "  ✅ Solo necesitas API REST"
echo "  ⏱️  Tiempo total: 30 minutos"
echo ""
echo "ELIGE JHIPSTER si:"
echo "  ✅ Proyecto a largo plazo"
echo "  ✅ Interfaz moderna necesaria"
echo "  ✅ Equipo grande"
echo "  ✅ Escalabilidad futura"
echo "  ⏱️  Tiempo total: 1-2 horas"
echo ""

echo "═════════════════════════════════════════════════════════════════════════"
echo ""
echo "🔗 URLS DE ACCESO"
echo "═════════════════════════════════════════════════════════════════════════"
echo ""
echo "QUARKUS:"
echo "  • Interfaz web:   http://localhost:8080/index.html"
echo "  • API REST:       http://localhost:8080/api/"
echo "  • Swagger UI:     http://localhost:8080/q/swagger-ui"
echo "  • BD Manager:     http://localhost:8081 (Adminer)"
echo ""
echo "JHIPSTER:"
echo "  • Frontend React: http://localhost:3000"
echo "  • Backend API:    http://localhost:8080"
echo "  • Swagger UI:     http://localhost:8080/swagger-ui/index.html"
echo "  • BD Manager:     http://localhost:8081 (Adminer)"
echo ""
echo "Credenciales por defecto:"
echo "  Usuario: admin"
echo "  Contraseña: admin"
echo ""

echo "═════════════════════════════════════════════════════════════════════════"
echo ""
echo "📚 DOCUMENTACIÓN DISPONIBLE"
echo "═════════════════════════════════════════════════════════════════════════"
echo ""
echo "📖 Documentos principales:"
echo "   1. README_PRINCIPAL.md           ← AQUÍ EMPEZAR"
echo "   2. COMPARATIVA_QUARKUS_JHIPSTER.md ← Análisis detallado"
echo ""
echo "📖 Documentación QUARKUS:"
echo "   • venta-cafe-api/README_INTERFAZ.md"
echo "   • venta-cafe-api/DOCKER_GUIA.md"
echo ""
echo "📖 Documentación JHIPSTER:"
echo "   • venta-cafe-jhipster/README_JHIPSTER.md"
echo "   • venta-cafe-jhipster/QUICKSTART.md"
echo ""

echo "═════════════════════════════════════════════════════════════════════════"
echo ""
echo "✅ CHECKLIST DE INICIO"
echo "═════════════════════════════════════════════════════════════════════════"
echo ""
echo "PARA QUARKUS:"
echo "  ☐ Docker Desktop instalado"
echo "  ☐ cd venta-cafe-api"
echo "  ☐ docker-compose up --build"
echo "  ☐ Esperar 30 segundos"
echo "  ☐ Abrir http://localhost:8080/index.html"
echo "  ⏱️  ~30 minutos"
echo ""
echo "PARA JHIPSTER:"
echo "  ☐ Node.js 18+ instalado"
echo "  ☐ Maven instalado"
echo "  ☐ JHipster global (npm install -g generator-jhipster)"
echo "  ☐ cd venta-cafe-jhipster"
echo "  ☐ ./generate.bat (o generate.sh)"
echo "  ☐ Esperar generación (~5 min)"
echo "  ☐ mvn spring-boot:run (Terminal 1)"
echo "  ☐ npm start (Terminal 2)"
echo "  ☐ Acceder a http://localhost:3000"
echo "  ⏱️  ~1.5 horas"
echo ""

echo "═════════════════════════════════════════════════════════════════════════"
echo ""
echo "🎉 ¡BIENVENIDO! Elige tu camino: 🚀"
echo ""
echo "  👉 RÁPIDO: venta-cafe-api (QUARKUS)"
echo "  👉 PROFESIONAL: venta-cafe-jhipster (JHIPSTER)"
echo ""
echo "═════════════════════════════════════════════════════════════════════════"
echo ""
